<?php require_once 'layouts/header.php' ?>

<div class="container no-inf ">
    <div class="col-md-4 col-md-offset-1">
        <h2 class="text-center">Order Info</h2>
        <h3 class="order-number">Order Number: <span></span></h3>
        <h3 class="order-total">Order Total: <span></span></h3>
        <h3 class="order-date">Order Date: <span></span></h3>
        <h3 class="order-status">Order Status: <span></span></h3>
    </div>

    <div class="col-md-4 col-md-offset-1">
        <h2 class="text-center">User Info</h2>
        <h3 class="user-firstname">Firstname: <span></span></h3>
        <h3 class="user-lastname">Lastname: <span></span></h3>
        <h3 class="user-email">Email: <span></span></h3>
        <h3 class="user-phone">Phone: <span></span></h3>
    </div>

</div>


<script>
    var UserId;

    // Get Order Info
    var order = new Firebase("https://shop-3cea1.firebaseio.com/Shop/order/<?=$orderId?>")

        .once('value', showOrder);

    function showOrder(snap) {

        var OrderInfo = snap.val();

        if(OrderInfo != null){

            UserId = OrderInfo.userId;

            var OrdStatus =  OrderInfo.OrderStatus;
            var statusText;

            if(OrdStatus == 1){
                statusText = 'Ordered';


                $('.order-number span').text(OrderInfo.OrderNumber);
                $('.order-total  span').text(OrderInfo.OrderTotal);
                $('.order-date   span').text(OrderInfo.OrderDate);
                $('.order-status span').text(statusText);

                callbackUser(UserId)

            }else if(OrdStatus == 2){
                $('.no-inf').html('<h3 class="text-center">The order is canceled</h3>');
            }

        }else{
            $('.no-inf').html(' <h3 class="text-center">No Information</h3>');
        }
        
    }
    
    // Get user Info
    function callbackUser(UserId) {

        var user = new Firebase("https://shop-a9add.firebaseio.com/Shop/user/"+UserId)

            .once('value', showUser);

        function showUser(snap) {

            var UserInfo = snap.val();

            $('.user-firstname span').text(UserInfo.FirstName);
            $('.user-lastname  span').text(UserInfo.LastName);
            $('.user-email     span').text(UserInfo.Email);
            $('.user-phone     span').text(UserInfo.Phone);
        }
    }
    

</script>

<?php require_once 'layouts/footer.php' ?>